// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFNgG_Scz3p-C02KyvWq4n9O5Pgx0yMt8',
    appId: '1:502026892163:web:7da3d83dbceaa2e1b3fcb6',
    messagingSenderId: '502026892163',
    projectId: 'fluttermonetizationcourse',
    authDomain: 'fluttermonetizationcourse.firebaseapp.com',
    storageBucket: 'fluttermonetizationcourse.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdDYqbTC4fenZUjgBDAGarVxuxksqT_8M',
    appId: '1:502026892163:android:41b96931ddfbacd1b3fcb6',
    messagingSenderId: '502026892163',
    projectId: 'fluttermonetizationcourse',
    storageBucket: 'fluttermonetizationcourse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVDC34n-7fp0Odf1h2fuXw8oL6JsX8NTA',
    appId: '1:502026892163:ios:3cfc32db72697850b3fcb6',
    messagingSenderId: '502026892163',
    projectId: 'fluttermonetizationcourse',
    storageBucket: 'fluttermonetizationcourse.appspot.com',
    iosBundleId: 'com.appskyloom.flutterMonetizationCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVDC34n-7fp0Odf1h2fuXw8oL6JsX8NTA',
    appId: '1:502026892163:ios:3cfc32db72697850b3fcb6',
    messagingSenderId: '502026892163',
    projectId: 'fluttermonetizationcourse',
    storageBucket: 'fluttermonetizationcourse.appspot.com',
    iosBundleId: 'com.appskyloom.flutterMonetizationCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFNgG_Scz3p-C02KyvWq4n9O5Pgx0yMt8',
    appId: '1:502026892163:web:404714d883531855b3fcb6',
    messagingSenderId: '502026892163',
    projectId: 'fluttermonetizationcourse',
    authDomain: 'fluttermonetizationcourse.firebaseapp.com',
    storageBucket: 'fluttermonetizationcourse.appspot.com',
  );
}
